Repository umco/umbraco-inner-content, pull requests merged in 2018-07, with the labels that each got.

#29 Added data-element to property
  src/Our.Umbraco.InnerContent/Web/UI/App_Plugins/InnerContent/views/innercontent.dialog.html
Labels: enhancement

#27 Adds a unique suffix to the tab ID
  src/Our.Umbraco.InnerContent/Web/UI/App_Plugins/InnerContent/js/innercontent.controllers.js
  src/Our.Umbraco.InnerContent/Web/UI/App_Plugins/InnerContent/views/innercontent.dialog.html
Labels: enhancement

#28 Adds Copy/Paste API
  src/Our.Umbraco.InnerContent/Web/UI/App_Plugins/InnerContent/js/innercontent.controllers.js
Labels: feature

#30 API for saving item as blueprint
  src/Our.Umbraco.InnerContent/Helpers/InnerContentHelper.cs
  src/Our.Umbraco.InnerContent/Web/Controllers/InnerContentApiController.cs
Labels: feature

#32 Preparing v1.1.2 release
  appveyor.yml
  src/Our.Umbraco.InnerContent/Helpers/InnerContentHelper.cs
  src/Our.Umbraco.InnerContent/PropertyEditors/InnerContentPropertyValueEditorWrapper.cs
  src/Our.Umbraco.InnerContent/Web/UI/App_Plugins/InnerContent/js/innercontent.controllers.js
  src/Our.Umbraco.InnerContent/Web/UI/App_Plugins/InnerContent/js/innercontent.resources.js
  src/Our.Umbraco.InnerContent/Web/UI/App_Plugins/InnerContent/views/innercontent.dialog.html
Labels: release
